### ISSUE TITLE
App v1.6 crashes

### ISSUE THREAD

**Issue by DenB000** [Ma7moud3ly/micro-repl#33]
Crashes while open script.

System report: 
java.lang.NoSuchMethodError: No virtual method toArray(Ljava/util/function/IntFunction;)[Ljava/lang/Object; in class Ljava/util/ArrayList; or its super classes (declaration of 'java.util.ArrayList' appears in /system/framework/core-oj.jar)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(SourceFile:250)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(SourceFile:259)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.c(SourceFile:1)
	at org.eclipse.tm4e.core.internal.rule.e.apply(SourceFile:1)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Unknown Source:10)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(Unknown Source:12)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(SourceFile:159)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(SourceFile:119)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.c(SourceFile:1)
	at org.eclipse.tm4e.core.internal.rule.e.apply(SourceFile:1)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Unknown Source:10)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(Unknown Source:12)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(SourceFile:159)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(SourceFile:119)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.c(SourceFile:1)
	at org.eclipse.tm4e.core.internal.rule.e.apply(SourceFile:1)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Unknown Source:10)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(Unknown Source:12)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(SourceFile:159)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(SourceFile:119)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.c(SourceFile:1)
	at org.eclipse.tm4e.core.internal.rule.e.apply(SourceFile:1)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Unknown Source:10)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(Unknown Source:12)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(SourceFile:159)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(SourceFile:259)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.c(SourceFile:1)
	at org.eclipse.tm4e.core.internal.rule.e.apply(SourceFile:1)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Unknown Source:10)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(Unknown Source:12)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(SourceFile:159)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(SourceFile:119)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.c(SourceFile:1)
	at org.eclipse.tm4e.core.internal.rule.e.apply(SourceFile:1)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Unknown Source:10)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(Unknown Source:12)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(SourceFile:159)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(SourceFile:119)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.c(SourceFile:1)
	at org.eclipse.tm4e.core.internal.rule.e.apply(SourceFile:1)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Unknown Source:10)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(Unknown Source:12)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory._compilePatterns(SourceFile:159)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.lambda$getCompiledRuleId$1(SourceFile:119)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.c(SourceFile:1)
	at org.eclipse.tm4e.core.internal.rule.e.apply(SourceFile:1)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.registerRule(Unknown Source:10)
	at org.eclipse.tm4e.core.internal.rule.RuleFactory.getCompiledRuleId(Unknown Source:12)
	at org.eclipse.tm4e.core.internal.grammar.Grammar._tokenize(Unknown Source:28)
	at org.eclipse.tm4e.core.internal.grammar.Grammar.tokenizeLine2(SourceFile:2)
	at x4.b.z(SourceFile:89)
	at o4.b.b(SourceFile:76)
	at o4.b.a(SourceFile:596)
	at o4.b.run(SourceFile:19)

**Comment by Ma7moud3ly** [comment]
I think this will be fixed after updating **desugar_jdk_libs** to latest. At  v2.1.0 they have added ```Support default method java.util.Collection#toArray(java.util.function.IntFunction```
https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md
